theme: jekyll-theme-cayman
title:       Topological Data Analysis and Beyond
description: Workshop at NeurIPS 2020

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Schedule: "/schedule"
  Speakers: "/speakers"
  Accepted Papers: "/papers"
  Organisers: "/organisers"
  Programme Committee: "/committee"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true
